// This is a server-side file.
'use server';

/**
 * @fileOverview Defines the flow for receiving concise and relevant answers from the chat agent.
 *
 * - receiveConciseAndRelevantAnswers - A function that handles the process of generating concise and relevant answers.
 * - ReceiveConciseAndRelevantAnswersInput - The input type for the receiveConciseAndRelevantAnswers function.
 * - ReceiveConciseAndRelevantAnswersOutput - The return type for the receiveConciseAndRelevantAnswers function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ReceiveConciseAndRelevantAnswersInputSchema = z.object({
  question: z.string().describe('The user question.'),
  context: z.string().describe('The relevant context retrieved from the knowledge base.'),
});
export type ReceiveConciseAndRelevantAnswersInput = z.infer<typeof ReceiveConciseAndRelevantAnswersInputSchema>;

const ReceiveConciseAndRelevantAnswersOutputSchema = z.object({
  answer: z.string().describe('The concise and relevant answer generated by the model.'),
});
export type ReceiveConciseAndRelevantAnswersOutput = z.infer<typeof ReceiveConciseAndRelevantAnswersOutputSchema>;

export async function receiveConciseAndRelevantAnswers(input: ReceiveConciseAndRelevantAnswersInput): Promise<ReceiveConciseAndRelevantAnswersOutput> {
  return receiveConciseAndRelevantAnswersFlow(input);
}

const prompt = ai.definePrompt({
  name: 'receiveConciseAndRelevantAnswersPrompt',
  input: {schema: ReceiveConciseAndRelevantAnswersInputSchema},
  output: {schema: ReceiveConciseAndRelevantAnswersOutputSchema},
  prompt: `You are a helpful assistant providing concise and relevant answers based on the given context.\n\nContext:\n{{context}}\n\nQuestion:\n{{question}}\n\nAnswer (concise and relevant):`,
});

const receiveConciseAndRelevantAnswersFlow = ai.defineFlow(
  {
    name: 'receiveConciseAndRelevantAnswersFlow',
    inputSchema: ReceiveConciseAndRelevantAnswersInputSchema,
    outputSchema: ReceiveConciseAndRelevantAnswersOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
